<?php
	// This plugin offers to set-up some standard server configurations for apache / NGINX
	// It may write the following files in the root directory
	// - .htaccess
	// - .htusers
	// - .index.html
	//
	// 'reset'          => server default 
	// 'setRedirection' => redirection to /system/index.php 
	// 'setBasicAuth'   => https + server basic auth + redirection to /system/index.php
	// 'setLoginPage'   => https + server basic auth + redirection to /system/index.php + custom login page
	
    $client='client.html';
	if(!isset($_GET['action'])){
        echo file_get_contents($client);
    }
    elseif($_GET['action']=='reset'){
        #HTACCESS
        $hta_res=unlink($_SERVER['DOCUMENT_ROOT'].'/.htaccess');
        #HTUSERS
        $htu_res=unlink($_SERVER['DOCUMENT_ROOT'].'/.htusers');
        #INDEX.HTML
        $index_res=unlink($_SERVER['DOCUMENT_ROOT'].'/.index.html');
		if($hta_res!==false && $htu_res!==false && $index_res!==false){echo "ok, No Authentication SET";}
        else {echo 'Error: '.$hta_res.'-'.$htu_res.'-'.$index_res;}
    }
    elseif($_GET['action']=='setRedirection'){
        #HTACCESS
        $htaccessContent="";
        $htaccessContent.="################"."\n";
        $htaccessContent.="### WARNING ####"."\n";
        $htaccessContent.="################"."\n";
        $htaccessContent.="# This file was generated automatically by 'Security 🔐' plugin"."\n";
        $htaccessContent.="# Do not edit by hand, it will be overwritten"."\n";
        $htaccessContent.="#"."\n";
        $htaccessContent.="# Indexes global configuration:"."\n";
        $htaccessContent.="# - Forbid listing of folder without a recognized index file"."\n";
        $htaccessContent.="# Define the only recognized index file as the static 'index.php' of the system folder"."\n";
        $htaccessContent.="# Trying to access the root of any folder will redirect to the system main page"."\n";
        $htaccessContent.="Options -Indexes"."\n";
        $htaccessContent.="DirectoryIndex /.index.html"."\n";
        $htaccessContent.=""."\n";
        $hta_res=file_put_contents($_SERVER['DOCUMENT_ROOT'].'/.htaccess',$htaccessContent);
        #HTUSERS
        $htu_res=unlink($_SERVER['DOCUMENT_ROOT'].'/.htusers');
        #INDEX.html
        $rootIndexContent="";
        $rootIndexContent.="<!DOCTYPE HTML>"."\n";
        $rootIndexContent.="<html lang=\"en-US\">"."\n";
        $rootIndexContent.="<head>"."\n";
        $rootIndexContent.="  <title>Page Redirection</title>"."\n";
        $rootIndexContent.="  <meta charset=\"UTF-8\">"."\n";
        $rootIndexContent.="  <meta http-equiv=\"refresh\" content=\"0; url=system/index.php\">"."\n";
        $rootIndexContent.="  <script type=\"text/javascript\">window.location.href = \"system/index.php\"</script>"."\n";
        $rootIndexContent.=  "</head>"."\n";
        $rootIndexContent.=    "<body>"."\n";
        $rootIndexContent.=    "<!-- WARNING: This file was generated automatically by 'Security 🔐' plugin. -->"."\n";
        $rootIndexContent.=    "<!-- Do not edit by hand, it will be overwritten. -->"."\n";
        $rootIndexContent.=    "<!-- Note: don't tell people to `click` the link, just tell them that it is a link. -->"."\n";
        $rootIndexContent.=    "If you are not redirected automatically, follow this <a href='system/index.php'>link</a>."."\n";
        $rootIndexContent.=  "</body>"."\n";
        $rootIndexContent.="</html>"."\n";
        $rootIndexContent.=""."\n";
        $index_res=file_put_contents($_SERVER['DOCUMENT_ROOT'].'/.index.html',$rootIndexContent);
		if($hta_res!==false && $htu_res!==false && $index_res!==false){echo "ok, Redirection set";}
        else {echo 'Error: '.$hta_res.'-'.$htu_res.'-'.$index_res;}
    }
    elseif($_GET['action']=='setBasicAuth'){
        $newPassword=$_GET['password'];
        if(is_string($newPassword)){
            if(strlen($newPassword)>0){
                // Here you can do any validation test you want on credentials
                if(strlen($newPassword)>3){
                    #HTACCESS
                    $htaccessContent="";
                    $htaccessContent.="################"."\n";
                    $htaccessContent.="### WARNING ####"."\n";
                    $htaccessContent.="################"."\n";
                    $htaccessContent.="# This file was generated automatically by 'Security 🔐' plugin"."\n";
					$htaccessContent.="# Do not edit by hand, it will be overwritten"."\n";
                    $htaccessContent.="#"."\n";
                    $htaccessContent.="# Indexes global configuration:"."\n";
                    $htaccessContent.="# - Forbid listing of folder without a recognized index file"."\n";
                    $htaccessContent.="# Define the only recognized index file as the static 'index.php' of the system folder"."\n";
                    $htaccessContent.="# Trying to access the root of any folder will redirect to the system main page"."\n";
                    $htaccessContent.="Options -Indexes"."\n";
                    $htaccessContent.="DirectoryIndex /.index.html"."\n";
                    $htaccessContent.=""."\n";
                    $htaccessContent.="# Force https protocol"."\n";
                    $htaccessContent.="RewriteEngine On"."\n";
                    $htaccessContent.="RewriteCond %{HTTPS} off"."\n";
                    $htaccessContent.="RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]"."\n";
                    $htaccessContent.=""."\n";
                    $htaccessContent.="# Authentication over HTTPS only"."\n";
                    $htaccessContent.="AuthType Basic"."\n";
                    $htaccessContent.="AuthName \"Authentication\""."\n";
                    $htaccessContent.="AuthUserFile ".$_SERVER['DOCUMENT_ROOT']."/.htusers"."\n";
                    $htaccessContent.="Order Deny,Allow"."\n";
                    $htaccessContent.="Deny from all"."\n";
                    $htaccessContent.="Satisfy Any"."\n";
                    $htaccessContent.="Allow from env=!HTTPS"."\n";
                    $htaccessContent.="Require valid-user"."\n";
                    $htaccessContent.=""."\n";
                    $htaccessContent.=""."\n";
                    $hta_res=file_put_contents($_SERVER['DOCUMENT_ROOT'].'/.htaccess',$htaccessContent);
                    #HTUSERS
                    //$htusersContent=hash('crc32',file_get_contents($_SERVER['DOCUMENT_ROOT'].'/SETTINGS_name.txt'),false).':'.crypt($newPassword,base64_encode($newPassword));
                    $htusersContent=':'.crypt($newPassword,base64_encode($newPassword))."\n";
                    $htusersContent.='pdm:'.crypt($newPassword,base64_encode($newPassword))."\n";
                    $htusersContent.='PDM:'.crypt($newPassword,base64_encode($newPassword))."\n";
                    $htu_res=file_put_contents($_SERVER['DOCUMENT_ROOT'].'/.htusers',$htusersContent);
                    #INDEX.html
                    $rootIndexContent="";
                    $rootIndexContent.="<!DOCTYPE HTML>"."\n";
					$rootIndexContent.="<html lang=\"en-US\">"."\n";
                    $rootIndexContent.="<head>"."\n";
                    $rootIndexContent.="  <title>Page Redirection</title>"."\n";
                    $rootIndexContent.="  <meta charset=\"UTF-8\">"."\n";
                    $rootIndexContent.="  <meta http-equiv=\"refresh\" content=\"0; url=system/index.php\">"."\n";
                    $rootIndexContent.="  <script type=\"text/javascript\">window.location.href = \"system/index.php\"</script>"."\n";
                    $rootIndexContent.=  "</head>"."\n";
                    $rootIndexContent.=    "<body>"."\n";
                    $rootIndexContent.=    "<!-- WARNING: This file was generated automatically by 'Security 🔐' plugin. -->"."\n";
                    $rootIndexContent.=    "<!-- Do not edit by hand, it will be overwritten. -->"."\n";
                    $rootIndexContent.=    "<!-- Note: don't tell people to `click` the link, just tell them that it is a link. -->"."\n";
                    $rootIndexContent.=    "If you are not redirected automatically, follow this <a href='system/index.php'>link</a>."."\n";
                    $rootIndexContent.=  "</body>"."\n";
                    $rootIndexContent.="</html>"."\n";
                    $rootIndexContent.=""."\n";
                    $index_res=file_put_contents($_SERVER['DOCUMENT_ROOT'].'/.index.html',$rootIndexContent);
                    if($hta_res!==false && $htu_res!==false && $index_res!==false){echo "ok, Basic Authentication SET\nThe login is \"pdm\"";}
                    else {echo 'Error: '.$hta_res.'-'.$htu_res.'-'.$index_res;}
                }else{echo 'Server Error: Passord does not match policy (at least 4 characters)';}
            }else{echo 'Server Error: Passord cannot be empty';}
        }else{echo 'Server Error: Password is not a string';}
    }
    elseif($_GET['action']=='setLoginPage'){
        $newPassword=$_GET['password'];
        echo 'not implemented yet';
    }
    else{
        echo "error unknown action";
    }
?>
